language: python
sudo: false

install:
  - pip install coverage coveralls tox
script:
  - tox
after_success:
  - coveralls

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
